# Generated by Django 3.2.5 on 2022-06-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=100)),
                ('endereço', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=100)),
                ('complemento', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=100)),
                ('descriçao', models.CharField(max_length=100)),
            ],
        ),
    ]
