# Generated by Django 3.2.5 on 2022-06-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_auto_20220615_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enderecos',
            name='cep',
            field=models.CharField(max_length=9),
        ),
    ]
